services:

  node_gateway:
    build: ./node_gateway
    volumes:
      - ./node_gateway:/app
      - /app/node_modules

  python_service:
    build: ./python_service
    volumes:
      - ./python_service:/app

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - node_gateway
